// SEED SCRIPT (Auto-generated by Antigravity)
// This script will clear (optional) and repopulate Habits and Classes/Rutinas based on the "Full Focus" schedule.

window.seedLifeSchedule = async function () {
    if (!confirm('⚠️ ¿Estás seguro? Esto creará todos tus hábitos y rutinas en la base de datos. (No borrará lo existente, solo añadirá).')) return;

    // Intentar obtener usuario de window.currentUser o directamente de Supabase
    let userId = window.currentUser?.id;

    if (!userId) {
        console.log('🔄 Consultando sesión de Supabase...');
        const { data: { user } } = await window.supabaseClient.auth.getUser();
        userId = user?.id;
    }

    if (!userId) {
        alert('❌ Error: No se detecta la sesión. Asegúrate de haber iniciado sesión y recarga la página.');
        return;
    }

    console.log('🚀 Iniciando Seed... Usuario:', userId);
    let logs = [];
    const log = (msg) => { console.log(msg); logs.push(msg); };

    // 1. HÁBITOS DIARIOS (Daily Habits)
    const habits = [
        { title: '☀️ Despertar 8AM' },
        { title: '💪 Ejercicio 8AM' },
        { title: '🚿 Bañarse 8:30AM' },
        { title: '🍳 Desayuno 9AM' },
        { title: '👨‍💻 Code Focus 9:30AM' },
        { title: '💎 OFFSZN Build 10:30AM' },
        { title: '🎬 Ordenar Guiones 12PM' },
        { title: '🇺🇸 Inglés Practice 1PM' },
        { title: '📖 Lectura 2PM' },
        { title: '🍽️ Comida 2:30PM' },
        { title: '📱 Admin Mode 7PM' },
        { title: '🥗 Cena 8PM' },
        { title: '🧠 Reflexión Nocturna' },
        { title: '😴 Dormir 10:30PM' }
    ];

    log('🌱 Creando hábitos...');
    for (const habit of habits) {
        const { error } = await window.supabaseClient
            .from('habits')
            .insert([{
                title: habit.title,
                completed_dates: [],
                user_id: userId,
                created_at: new Date().toISOString()
            }]);

        if (error) log(`❌ Error hábito ${habit.title}: ${error.message}`);
        else log(`✅ Hábito creado: ${habit.title}`);
    }

    // 2. CLASES / BLOQUES FIJOS (Usaremos la tabla 'classes' para bloques de tiempo fijos)
    // Lunes = 1, Martes = 2... Domingo = 7? No, usually Lunes-Viernes checkboxes.
    // 'classes' table structure based on app.js: subject, day, startTime, endTime, room(optional)

    const scheduleBlocks = [
        // L-M-V Inglés
        { subject: '🇺🇸 English Class', day: 'Lunes', startTime: '16:00', endTime: '19:00', room: 'Academia' },
        { subject: '🇺🇸 English Class', day: 'Miércoles', startTime: '16:00', endTime: '19:00', room: 'Academia' },
        { subject: '🇺🇸 English Class', day: 'Viernes', startTime: '16:00', endTime: '19:00', room: 'Academia' },

        // M-J Deep Work
        { subject: '🚀 DEEP WORK OFFSZN', day: 'Martes', startTime: '15:30', endTime: '19:00', room: 'Home' },
        { subject: '🚀 DEEP WORK OFFSZN', day: 'Jueves', startTime: '15:30', endTime: '19:00', room: 'Home' },

        // S-D Edición
        { subject: '🎥 FULL EDICIÓN', day: 'Sábado', startTime: '15:30', endTime: '20:00', room: 'Studio' },
        { subject: '🎥 FULL EDICIÓN', day: 'Domingo', startTime: '15:30', endTime: '20:00', room: 'Studio' },

        // Noches OFFSZN (L-M-V-S-D)
        { subject: '🌐 OFFSZN Web', day: 'Lunes', startTime: '20:30', endTime: '21:30', room: 'Home' },
        { subject: '🌐 OFFSZN Web', day: 'Miércoles', startTime: '20:30', endTime: '21:30', room: 'Home' },
        { subject: '🌐 OFFSZN Web', day: 'Viernes', startTime: '20:30', endTime: '21:30', room: 'Home' },
        { subject: '💎 OFFSZN Code', day: 'Sábado', startTime: '20:30', endTime: '21:30', room: 'Home' },
        { subject: '💎 OFFSZN Code', day: 'Domingo', startTime: '20:30', endTime: '21:30', room: 'Home' },

        // Noches Assets (M-J)
        { subject: '✍️ Guiones & Assets', day: 'Martes', startTime: '20:30', endTime: '21:30', room: 'Home' },
        { subject: '✍️ Guiones & Assets', day: 'Jueves', startTime: '20:30', endTime: '21:30', room: 'Home' },
    ];

    log('📅 Agendando bloques semanales...');
    for (const block of scheduleBlocks) {
        const { error } = await window.supabaseClient
            .from('classes')
            .insert([{
                subject: block.subject,
                day: block.day,
                startTime: block.startTime,
                endTime: block.endTime,
                room: block.room,
                user_id: userId,
                created_at: new Date().toISOString()
            }]);

        if (error) log(`❌ Error bloque ${block.day} ${block.subject}: ${error.message}`);
        else log(`✅ Bloque creado: ${block.day} - ${block.subject}`);
    }

    alert('✨ ¡Proceso terminado! Revisa la consola para detalles.');
    window.location.reload(); // Recargar para ver cambios
};
